# Generated by Django 5.1.6 on 2026-08-14 07:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name_uz', models.CharField(max_length=64)),
                ('name_ru', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('wifi_speed', models.CharField(choices=[('none', 'none'), ('slow', 'slow'), ('medium', 'medium'), ('fast', 'fast')], default='medium', max_length=20)),
                ('outlets_level', models.CharField(choices=[('none', 'none'), ('few', 'few'), ('every_table', 'every_table')], default='few', max_length=20)),
                ('noise_level', models.CharField(choices=[('very_quiet', 'very_quiet'), ('quiet', 'quiet'), ('moderate', 'moderate'), ('noisy', 'noisy')], default='quiet', max_length=20)),
                ('price_level', models.CharField(choices=[('free', 'free'), ('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='free', max_length=10)),
                ('working_hours', models.JSONField(default=dict)),
                ('amenities', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='places.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='places.place')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='places.place')),
            ],
            options={
                'unique_together': {('user', 'place')},
            },
        ),
    ]
